feat: bounce interfaces once configs are in place
Regardless of whether the interface configuration has changed the
interfaces will be bounced taking them down and then bringing them back
up.

diff --git a/tasks/main.yml b/tasks/main.yml
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -28,3 +28,18 @@
     mode: "0644"
   with_items: "{{ vxlan_interfaces }}"
   become: true
+
+- name: Bounce network interfaces
+  ansible.builtin.command: >
+    nohup bash -c "
+    returncode=0
+    ifdown {{ item.device }};
+    if ! ifup {{ item.device }}; then
+      echo \"Encountered an error attempting to bring up interface: {{ item.device }}\";
+      returncode=1
+    fi;
+    exit $returncode
+    "
+  with_items: "{{ vxlan_interfaces }}"
+  changed_when: true
+  become: true
