feat: modify vlxan script to ignore interface if already exists

diff --git a/files/ifup-vxlan b/files/ifup-vxlan
--- a/files/ifup-vxlan
+++ b/files/ifup-vxlan
@@ -15,11 +15,13 @@ source_config
 
 /etc/sysconfig/network-scripts/ifup ${PHYS_DEV}
 
-ip link add ${DEVICE} type vxlan \
-        id ${VNI} \
-        group ${GROUP} \
-        ttl ${TTL:-10} \
-        dev ${PHYS_DEV} \
-        dstport ${PORT:-4789}
+if ! ip link show dev ${DEVICE} >/dev/null 2>&1 ; then
+    echo "Creating vxlan ${DEVICE} - VNI: ${VNI}, IP Address: ${IPADDR}/${PREFIX}"
+    ip link add ${DEVICE} type vxlan id ${VNI} group ${GROUP} ttl ${TTL:-10} dev ${PHYS_DEV} dstport ${PORT:-4789}
+    if [[ $? -ne 0 ]]; then
+        echo "Failed creating vxlan"
+        exit 1
+    fi
+fi
 
 /etc/sysconfig/network-scripts/ifup-eth ${DEVICE}
